# Generated by Django 5.2.8 on 2025-11-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_usuario_clcb_usuario_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clcb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
