# Generated by Django 5.2.8 on 2025-11-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_alter_usuario_clcb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clcb',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Incendio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('local', models.CharField(max_length=200)),
                ('gravidade', models.CharField(choices=[('grave', 'Grave'), ('medio', 'Médio'), ('baixo', 'Baixo')], max_length=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.usuario')),
            ],
        ),
    ]
