# Generated by Django 5.2.8 on 2025-11-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_alter_usuario_clcb_alter_usuario_senha_incendio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incendio',
            name='gravidade',
            field=models.CharField(choices=[('grave', 'Grave'), ('medio', 'Médio'), ('baixo', 'Baixo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incendio',
            name='local',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='incendio',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_app.usuario'),
        ),
    ]
