# Generated by Django 5.2.8 on 2025-11-21 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_alter_incendio_gravidade_alter_incendio_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incendio',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud_app.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='clcb',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
